# TensorFlow


In [1]:
import tensorflow as tf

A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes

# Creating tensors

In [4]:
string = tf.Variable ("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.5, tf.float64)

### Tensors of higher degrees/ranks

In [14]:
rank1_tensor = tf.Variable(['test', 'ok'], tf.string) #1 dimension
rank2_tensor = tf.Variable([["test", "ok",'hola'], ['val', 'ok', "chau"]], tf.string)

### Determine the rank of a tensor

In [8]:
tf.rank(rank2_tensor) 

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of a tensor

In [15]:
rank2_tensor.shape #2 lists of 3 elements 

TensorShape([2, 3])

### Changing the shape of a tensor

In [17]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


I can see a list with two lists inside, with 3 elements [ [  , , ]  [  , , ]]

In [21]:
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshape existing data to shape [2,3,1]
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [23]:
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place

print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors

- Variable
- Constant
- Placeholder
- SparseTensor
- With the exception of Variable, all of these tensors are immutable, meaning their value may not change during execution.

### Evaluating Tensors

In [28]:
tf.compat.v1.disable_eager_execution()
tensor = tf.constant(3)
with tf.compat.v1.Session() as sess:
    result = tensor.eval() #tensor will be the name of your tensor

https://www.tensorflow.org/guide/tensor